version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  webapp:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
